---
- name: Test Create Bridge Domain
  hosts: apic
  gather_facts: no
  connection: httpapi
  tasks:

    - name: Login to APIC and get session cookie
      uri:
        url: "https://{{ ansible_host }}/api/aaaLogin.json"
        method: POST
        validate_certs: no
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          aaaUser:
            attributes:
              name: "{{ user }}"
              pwd: "{{ password }}"
      register: login_response

    - name: Display Login Response
      debug:
        var: login_response
 

    - name: Create bridge domain
      uri:
        url: "https://{{ ansible_host }}/api/mo/uni/tn-MyTenant/BD-yupyup.json"
        method: POST
        validate_certs: no
        headers:
          Content-Type: "application/json"
          Cookie: "APIC-Cookie={{ login_response['cookies']['APIC-cookie'] }}"
        body_format: json
        body:
          fvBD:
            attributes:
              dn: "uni/tn-MyTenant/BD-yupyup"
              arpFlood: "true"
              mac: "00:22:BD:F8:19:FF"
              name: "yupyup"
              rn: "BD-yupyup"
              status: "created"
            children: []
      register: response

    - name: Display Response
      debug:
        var: response

